NUM_EXAMPLES_TRAIN: 100 # use -1 for all
NUM_EXAMPLES_VAL: 100 # use -1 for all
NUM_EPOCHS: 100
INPUT_SIZE: 784
OUTPUT_SIZE: 10
NUM_NEURONS_PER_COLUMN: 200
NUM_CONNECTIONS_PER_NEURON: 10
SPIKE_THRESHOLD: 1000000
MAX_UPDATE_THRESHOLD: 3000  # not used right now
INITIAL_CONNECTION_WEIGHT: False
INITIAL_CONNECTION_WEIGHT_DELTA_MIN: 0
INITIAL_CONNECTION_WEIGHT_DELTA_MAX: 1
POSITIVE_REINFORCE_AMOUNT: 100
NEGATIVE_REINFORCE_AMOUNT: 5
POSITIVE_QUANTILIZER_INC_VALUE: 19
POSITIVE_QUANTILIZER_DEC_VALUE: 1
POSITIVE_QUANTILIZER_DENOM: 100
NEGATIVE_QUANTILIZER_INC_VALUE: 150
NEGATIVE_QUANTILIZER_DEC_VALUE: 1
NEGATIVE_QUANTILIZER_DENOM: 900
DECAY_AMOUNT: 0 # For now...
PRUNE_WEIGHT: 97000
FILTER_THRESHOLDS:
  1
  64
  128
  192
SHUFFLE_BATCHES: True
LOG_LEVEL: ERROR
DEVICE: auto
RANDOM_SEED: 42
WANDB_TAGS:
  testing
  single_quant
  float
WANDB_MODE: online
UPDATE_PBAR_N_TIMES_PER_EPOCH: 10