NUM_EXAMPLES_TRAIN: -1 # use -1 for all
NUM_EXAMPLES_VAL: -1 # use -1 for all
NUM_EPOCHS: 100
INPUT_SIZE: 784
OUTPUT_SIZE: 10
NUM_NEURONS_PER_COLUMN: 200
NUM_CONNECTIONS_PER_NEURON: 10
SPIKE_THRESHOLD: 1000
MAX_UPDATE_THRESHOLD: 3000
POSITIVE_REINFORCE_AMOUNT: 100
NEGATIVE_REINFORCE_AMOUNT: 5
DECAY_AMOUNT: 0 # For now...
PRUNE_WEIGHT: -5
LOG_LEVEL: ERROR
DEVICE: auto
RANDOM_SEED: 42
FILTER_THRESHOLDS:
  1
  64
  128
  192
WANDB_TAGS: testing,hello_world
WANDB_MODE: online
UPDATE_PBAR_EVEY_N_SAMPLES: 200