training:
  num_examples_train: -1 # use -1 for all
  num_examples_Val: -1 # use -1 for all
  num_epochs: 100
  shuffle_batches: True
network:
  input_size: 784
  output_size: 10
  num_neurons_per_column: 200
  num_connections_per_column: 10
  spike_threshold: 1000000
  max_update_threshold: 3000  # not used right now
  initial_connection_weight:
    weight_value: False
    delta_min: 0
    delta_max: 1
  positive_reinforce_amount: 100
  negative_reinforce_amount: 5
  positive_quantilizer:
    inc_value: 19
    dec_value: 1
    denom: 100
  negative_quantilizer:
    inc_value: 150
    dec_value: 1
    denom: 900
  decay_amount: 0 # For now...
  prune_weight: -5
preprocessing:
  pixel_intensity_levels:
    1
    64
    128
    192
general:
  log_level: ERROR
  update_pbar_n_times_per_epoch: 100
  device: auto
  random_seed: 42
wandb:
  tags:
    testing
    single_quant
    float
  mode: online
